#!/bin/sh

set -e

# some version prior to 2.22.2-3 started shipping /var/lib/scrollkeeper
# erroneously, hence the database was overwritten and needs a full rebuild
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt-nl "2.22.2-3" && which scrollkeeper-rebuilddb >/dev/null 2>&1; then
    echo "Upgrade from broken Cheese version detected, running scrollkeeper-rebuilddb..."
    scrollkeeper-rebuilddb -q
fi

#DEBHELPER#

