.TH "cheese" "1"
.SH "NAME"
cheese \- A tool to take pictures and videos from your webcam
.SH "SYNOPSIS"
\fB
.SH "DESCRIPTION"
.B cheese
is a cheesy program to take pictures and videos from your web
cam. It also provides some graphical effects in order to please the
users play instinct. 
.SH "AUTHOR"
.PP
This manual page was written by Cody A.W. Somerville <cody-somerville@ubuntu.com> 
for the \fBUbuntu GNU/Linux\fP system.

